name: Deployment

on:
  pull_request:
    branches:
      - main
      - develop
    types: [closed]
    paths:
      - 'current/**'
  push:
    branches:
      - develop
    paths:
      - 'current/stag/**'

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

jobs:
  deploy:
    if: (github.event.pull_request.merged == true) || (github.event_name == 'push')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy htmls (Staging)
        if: (github.base_ref == 'develop') || ((github.event_name == 'push') && (github.ref_name == 'develop'))
        uses: reggionick/s3-deploy@v3
        with:
          folder: current/stag
          bucket: app-testnets.thespace.game
          bucket-region: ap-southeast-1
          dist-id: EVWV6S8G4YU1I
          invalidation: /*
          private: true
          files-to-include: "*html"

      - name: Deploy static assets (Staging)
        if: (github.base_ref == 'develop') || ((github.event_name == 'push') && (github.ref_name == 'develop'))
        uses: reggionick/s3-deploy@v3
        with:
          folder: current/stag
          bucket: app-testnets.thespace.game
          bucket-region: ap-southeast-1
          dist-id: EVWV6S8G4YU1I
          invalidation: /*
          private: true
          files-to-include: "*[sg]"
          cache: 31536000

      - name: Deploy htmls (Production)
        if: github.base_ref == 'main'
        uses: reggionick/s3-deploy@v3
        with:
          folder: current/prod
          bucket: app.thespace.game
          bucket-region: ap-southeast-1
          dist-id: E29ZFXXINKSOH
          invalidation: /*
          private: true
          files-to-include: "*html"

      - name: Deploy static assets (Production)
        if: github.base_ref == 'main'
        uses: reggionick/s3-deploy@v3
        with:
          folder: current/prod
          bucket: app.thespace.game
          bucket-region: ap-southeast-1
          dist-id: E29ZFXXINKSOH
          invalidation: /*
          private: true
          files-to-include: "*[sg]"
          cache: 31536000
